### ISSUE TITLE
maven-compiler 3.1 only downward compatible for versions 1.6 - 3.1

### ISSUE THREAD

**Issue by NickNVM** [INF16A/SE4_Airplane#40]
maven-compiler 3.1 does not support maven-compiler versions below 1.6

``[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project 13_airconditioning: Compilation failure: Compilation failure:
[ERROR] Source option 1.5 is no longer supported. Use 1.6 or later.``

**Comment by carstenhag** [comment]
Dange

**Comment by carstenhag** [comment]
Ich machs mal zu ohne zu fragen 😊
